version: '3.3'
services:
  db:
    image: mariadb:latest
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: prestashop
      MYSQL_USER: pts_usr
      MYSQL_PASSWORD: 1234
  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:latest
    restart: 'no'
    ports:
      - '9080:80'
    environment:
      DB_SERVER: db
      DB_USER: pts_usr
      DB_NAME: prestashop
      DB_PASSWD: 1234
      DB_PREFIX: ps_
      PS_DOMAIN: "localhost:8080"
      
